filebeat.inputs:
  - type: filestream
    id: {{ component }}
    enabled: true
    paths:
      - {{ log_file }}
    fields:
      component: {{ component }}

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

output.elasticsearch:
  hosts: ["172.31.85.23:9200"]


processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
