- name: Create Application User
  ansible.builtin.user:
    name: "{{app_user}}"

- name: Clean Old App content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create Application directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download Application Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: true
